[package]
name = "backend-doctor-fix"
description.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
backend-doctor-core = { path = "../backend-doctor-core", version = "0.1.0" }
serde.workspace = true
